# Generated by Django 6.0.7 on 2026-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('tel_client', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('type_appareil', models.CharField(max_length=100, verbose_name="Type d'appareil (TV, Drone, etc.)")),
                ('panne_constatee', models.TextField(verbose_name='Panne constatée')),
                ('prix_devis', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix du devis (FCFA)')),
                ('avance_versee', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Avance versée (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'arrivée")),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Prêt', 'Prêt'), ('Terminé', 'Terminé')], default='En attente', max_length=50)),
            ],
        ),
    ]
