# Generated by Django 6.0.7 on 2026-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='composants_changes',
            field=models.TextField(blank=True, verbose_name='Composants/Pièces changés'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cout_pieces',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Coût total des pièces (FCFA)'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='technicien_en_charge',
            field=models.CharField(default='Non assigné', max_length=100, verbose_name='Technicien assigné'),
            preserve_default=False,
        ),
    ]
